### ISSUE TITLE
Will canetis work for other languages as well?????

### ISSUE THREAD

**Issue by youzarsifbutt** [nsheth12/canetis#8]

**Comment by ghodouss** [comment]
Canetis is a wrapper on top of the Gentle Forced Alignment Engine. Based on their homepage, it seems to me that Gentle has currently only been trained on English:
> Technique:
We construct a language model composed of all bigrams within the provided transcript, and combine it with an acoustic model (trained by Kaldi developers on the Fisher  English corpus). After running online transcription, we use sequence alignment algorithms to match the result with the original transcript.

Link: https://lowerquality.com/gentle/

**Comment by ruohoruotsi** [comment]
It will not work for other languages. The [Speech recognition system that gentle uses](http://kaldi-asr.org/models/m1) emits English text, so the transcripts supported for alignment need to be in English as well. 

If you want additional languages, you can swap out the English speech model for another (say [Mandarin](http://kaldi-asr.org/models/m2)), and do any extra work to support language modeling in the new language, esp if the character set and spelling requires different or extra handling (beyond what is necessary for English)
